java.naming.factory.url.pkgs=org.jboss.ejb.client.naming
remote.connectionprovider.create.options.org.xnio.Options.SSL_ENABLED=false

remote.connections=default

remote.connection.default.host=172.16.67.13
remote.connection.default.port=4889
remote.connection.default.connect.options.org.xnio.Options.SASL_POLICY_NOANONYMOUS=false

remote.connection.default.connect.timeout=60000

# Disable JNDI auto discovery
jnp.disableDiscovery=true

MAINTAIN_MESSAGE_SESSION_EJB_JNDI_NAME=ejb:dci-cmc-app/dci-cmc-ejb/MaintainMessageSessionEJB!hk.gov.cmc.appserver.ejb.session.maintainmessage.IMaintainMessageSessionBMRemote
ASYN_MESSAGE_SESSION_EJB_JNDI_NAME=ejb:dci-cmc-app/dci-cmc-ejb/AsynMessageSessionEJB!hk.gov.cmc.appserver.ejb.session.asynmessage.IAsynMessageSessionBMRemote
IAS_MSG_SETTING_SESSION_EJB_JNDI_NAME=ejb:dci-cmc-app/dci-cmc-ejb/IasMsgSettingSessionEJB!hk.gov.cmc.appserver.ejb.session.iasmessage.IIasMsgSettingSessionBMRemote
HOUSE_KEEPING_RECORD_SESSION_EJB_JNDI_NAME=ejb:dci-cmc-app/dci-cmc-ejb/HouseKeepingRecordSessionEJB!hk.gov.cmc.appserver.ejb.session.housekeep.IHouseKeepingRecordSessionBMRemote
# REPORTFW_REMOTE_EJB_JNDI_NAME=ejb:cmc/reportfw_ejb3/FwReportSessionEJB!hk.gov.ogcio.mars_cmc.reportfw.appserver.ejb.session.IFwReportSessionBM
BATCHFW_REMOTE_EJB_JNDI_NAME=ejb:dci-cmc-app/dci-cmc-ejb/FwBatchSessionEJB!hk.gov.cmc.appserver.ejb.session.batchfw.IFwBatchSessionBM
