
package hk.gov.cmc.common;

public class CmcAppPropertyNames {

    public static final String MAINT_MSG_REQ_RECIPIENT_APP_ID_PROPERTY_NAME = "MAINT_MSG_REQ_RECIPIENT_APP_ID";

    public static final String MAINT_MSG_REQ_SENDER_APP_TYPE_PROPERTY_NAME = "MAINT_MSG_REQ_SENDER_APP_TYPE";

    public static final String MAINT_MSG_REQ_RECIPIENT_APP_TYPE_PROPERTY_NAME = "MAINT_MSG_REQ_RECIPIENT_APP_TYPE";

    public static final String TO_DO_ITEM_IMPORTANT_DT_UPPER_LIMIT_PROPERTY_NAME = "TO_DO_ITEM_IMPORTANT_DT_UPPER_LIMIT";

    public final static String WS_AUTH_TYPE_PROPERTY = "WS_AUTH_TYPE";

    public final static String WS_WSS_USER_PROPERTY = "WS_WSS_USER";

    public final static String FRIENDLY_KEY_ALIAS_PROPERTY = "FRIENDLY_KEY_ALIAS";

    public final static String TRUST_KEY_ALIAS_PROPERTY = "TRUST_KEY_ALIAS";

    public final static String CMC_SCOPES_SENDER_APP_ID_PROPERTY = "CMC_SCOPES_SENDER_APP_ID";

    public final static String CMC_SCOPES_SENDER_APP_TYPE_PROPERTY = "CMC_SCOPES_SENDER_APP_TYPE";

    public final static String CMC_SCOPES_RECIPIENT_APP_ID_PROPERTY = "CMC_SCOPES_RECIPIENT_APP_ID";

    public final static String CMC_SCOPES_RECIPIENT_APP_TYPE_PROPERTY = "CMC_SCOPES_RECIPIENT_APP_TYPE";

    public final static String XML_REPORT_SEND_ASYN_SP_ID_LIST_PROPERTY = "XML_REPORT_SEND_ASYN_SP_ID_LIST";

    public final static String UNDELIVER_REPORT_REQ_SENDER_APP_TYPE_PROPERTY = "UNDELIVER_REPORT_REQ_SENDER_APP_TYPE";
    public final static String UNDELIVER_REPORT_REQ_SENDER_APP_ID_PROPERTY = "UNDELIVER_REPORT_REQ_SENDER_APP_ID";
    public final static String UNDELIVER_REPORT_REQ_RECIPIENT_APP_TYPE_PROPERTY = "UNDELIVER_REPORT_REQ_RECIPIENT_APP_TYPE";
    public final static String UNDELIVER_REPORT_REQ_RECIPIENT_APP_ID_PROPERTY = "UNDELIVER_REPORT_REQ_RECIPIENT_APP_ID";

    public final static String MAINT_MSG_SINGLE_PULL_CALL_LIMIT_PROPERTY = "MAINT_MSG_SINGLE_PULL_CALL_LIMIT";

    public final static String MAINT_MSG_SUBJ_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_SUBJ_SIZE_LIMIT";
    public final static String MAINT_MSG_CONTENT_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_CONTENT_SIZE_LIMIT";

    public final static String MAINT_MSG_EMAIL_SUBJ_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_EMAIL_SUBJ_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_EMAIL_SUBJ_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_EMAIL_SUBJ_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_EMAIL_CONTENT_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_EMAIL_CONTENT_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_EMAIL_CONTENT_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_EMAIL_CONTENT_CHI_SIZE_LIMIT";

    public final static String MAINT_MSG_MOBILE_SUBJ_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_MOBILE_SUBJ_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_MOBILE_SUBJ_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_MOBILE_SUBJ_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_MOBILE_CONTENT_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_MOBILE_CONTENT_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_MOBILE_CONTENT_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_MOBILE_CONTENT_CHI_SIZE_LIMIT";

    public final static String INTERNET_EMAIL_MAX_BATCH_SIZE_PROPERTY_NAME = "INTERNET_EMAIL_MAX_BATCH_SIZE";
    public final static String INTERNET_EMAIL_MAX_SLEEP_TIME_MS_PROPERTY_NAME = "INTERNET_EMAIL_MAX_SLEEP_TIME_MS";
    public final static String INTERNET_EMAIL_NOTI_WS_DEFAULT_SINGLE_TIME_MS_PROPERTY_NAME = "INTERNET_EMAIL_NOTI_WS_DEFAULT_SINGLE_TIME_MS";
    public final static String INTERNET_EMAIL_NOTI_WS_DEFAULT_BATCH_TIME_MS_PROPERTY_NAME = "INTERNET_EMAIL_NOTI_WS_DEFAULT_BATCH_TIME_MS";
    public final static String INTERNET_EMAIL_REMOVE_USER_PROFILE_INFO_IND_PROPERTY_NAME = "INTERNET_EMAIL_REMOVE_USER_PROFILE_INFO_IND";

    public final static String BILL_CENTER_PAY_TRAN_SOAP_ACTION_PROPERTY = "BILL_CENTER_PAY_TRAN_SOAP_ACTION";
    public final static String BILL_CENTER_PAY_TRAN_END_POINT_PROPERTY = "BILL_CENTER_PAY_TRAN_END_POINT";

    public final static String JOB_CONTROL_TIMEOUT_CHECK_NEEDED_PROPERTY_SUFFIX = "_TIMEOUT_CHECK_NEEDED";
    public final static String JOB_CONTROL_TIMEOUT_MINS_PROPERTY_SUFFIX = "_TIMEOUT_MINS";
    public final static String JOB_CONTROL_MAINT_MSG_PROPERTY_NAME = "JOB_CONTROL_MAINT_MSG";
    public final static String JOB_CONTROL_RECON_LS_PROPERTY_NAME = "JOB_CONTROL_RECON_LS";
    public final static String JOB_CONTROL_RECON_AP_PROPERTY_NAME = "JOB_CONTROL_RECON_AP";
    public final static String JOB_CONTROL_BILL_ACC_UPDATE_PROPERTY_NAME = "JOB_CONTROL_BILL_ACC_UPDATE";
    public final static String JOB_CONTROL_GEN_BCPTF_PROPERTY_NAME = "JOB_CONTROL_GEN_BCPTF";
    public final static String JOB_CONTROL_INTERNET_EMAIL_PROPERTY_NAME = "JOB_CONTROL_INTERNET_EMAIL";
    public final static String JOB_CONTROL_BCPTF_RESP_PROPERTY_NAME = "JOB_CONTROL_BCPTF_RESP";
    public final static String JOB_CONTROL_SEND_MSG_TO_MOBILE_NOTI = "JOB_CONTROL_SEND_MSG_MOBILE_NOTI";
    public final static String JOB_CONTROL_RETRIEVE_RESP_FR_MOBILE_NOTI = "JOB_CONTROL_RETR_RESP_MOBILE_NOTI";
    public final static String JOB_CONTROL_PREPARE_PERSONAL_EMAIL_BATCH_PROPERTY_NAME = "JOB_CONTROL_PREP_PERSONAL_EMAIL_BATCH";
    public final static String JOB_CONTROL_PREPARE_PERSONAL_EMAIL_BULK_PROPERTY_NAME = "JOB_CONTROL_PREP_PERSONAL_EMAIL_BULK";
    public final static String JOB_CONTROL_SEND_PERSONAL_EMAIL_PROPERTY_NAME = "JOB_CONTROL_SEND_PERSONAL_EMAIL";
    public final static String JOB_CONTROL_SEND_BROADCAST_EMAIL_BATCH_PROPERTY_NAME = "JOB_CONTROL_SEND_BROADCAST_EMAIL_BATCH";
    public final static String JOB_CONTROL_SEND_BROADCAST_EMAIL_BULK_PROPERTY_NAME = "JOB_CONTROL_SEND_BROADCAST_EMAIL_BULK";
    public final static String JOB_CONTROL_NOTI_JOB_CLEANUP_PROPERTY_NAME = "JOB_CONTROL_NOTI_JOB_CLEANUP";
    public final static String JOB_CONTROL_RELOCATE_FINAL_RECORD_PROPERTY_NAME = "JOB_CONTROL_RELOCATE_FINAL_RECORD";
    public final static String JOB_CONTROL_HOUSE_KEEP_PROPERTY_NAME = "JOB_CONTROL_HOUSE_KEEP";
    public final static String JOB_CONTROL_PUBLIC_HOLIDAY_PROPERTY_NAME = "JOB_CONTROL_PUBLIC_HOLIDAY";
    public final static String JOB_CONTROL_GEN_ADMIN_REPORT_PROPERTY_NAME = "JOB_CONTROL_GEN_ADMIN_REPORT";
    public final static String JOB_CONTROL_REGEN_ADMIN_BATCH_REPORT_PROPERTY_NAME = "JOB_CONTROL_REGEN_ADMIN_BATCH_REPORT";
    public final static String JOB_CONTROL_SEND_IAS_NOTI_PROPERTY_NAME = "JOB_CONTROL_SEND_IAS_NOTI";
    public final static String JOB_CONTROL_GET_IAS_NOTI_RESULT_PROPERTY_NAME = "JOB_CONTROL_GET_IAS_NOTI_RESULT";
    public final static String JOB_CONTROL_SEND_IAS_TO_DO_ITEM_NOTI_PROPERTY_NAME = "JOB_CONTROL_SEND_IAS_TO_TO_ITEM_NOTI";
    public final static String JOB_CONTROL_GET_IAS_TO_DO_ITEM_NOTI_RESULT_PROPERTY_NAME = "JOB_CONTROL_GET_IAS_TO_DO_ITEM_NOTI_RESULT";
    public final static String JOB_CONTROL_SEND_IAS_APPLICATION_NOTI_PROPERTY_NAME = "JOB_CONTROL_SEND_IAS_APPLICATION_NOTI";
    public final static String JOB_CONTROL_GET_IAS_APPLICATION_NOTI_RESULT_PROPERTY_NAME = "JOB_CONTROL_GET_IAS_APPLICATION_NOTI_RESULT";
    public final static String JOB_CONTROL_DELETE_DEREG_IAS_USER_MSG_PROPERTY_NAME = "JOB_CONTROL_DELETE_DEREG_IAS_USER_MSG";
    public final static String JOB_CONTROL_UNCONSENT_DELETE_TO_DO_ITEM_PROPERTY_NAME = "JOB_CONTROL_UNCONSENT_DELETE_TO_DO_ITEM";
    public final static String JOB_CONTROL_UNCONSENT_DELETE_APPLICATION_PROPERTY_NAME = "JOB_CONTROL_UNCONSENT_DELETE_APPLICATION";

    public final static String MOBILE_NOTI_OVERRUN_THRESHOLD = "MOBILE_NOTI_OVERRUN_THRESHOLD";

    public final static String HOUSE_KEEP_MYMSG_MONTH_LIMIT_PROPERTY_NAME = "HOUSE_KEEP_MYMSG_MONTH_LIMIT";
    public final static String HOUSE_KEEP_TODO_MONTH_LIMIT_PROPERTY_NAME = "HOUSE_KEEP_TODO_MONTH_LIMIT";
    public final static String HOUSE_KEEP_PAYTRAN_MONTH_LIMIT_PROPERTY_NAME = "HOUSE_KEEP_PAYTRAN_MONTH_LIMIT";
    public final static String HOUSE_KEEP_BATCH_SIZE_PROPERTY_NAME = "HOUSE_KEEP_BATCH_SIZE";
    public final static String HOUSE_KEEP_DEL_NON_USER_TBL_MONTH_LIMIT_PROPERTY_NAME = "HOUSE_KEEP_DEL_NON_USER_TBL_MONTH_LIMIT";

    public final static String MARK_TRASHED_DEL_MYMSG_MONTH_LIMIT_PROPERTY_NAME = "MARK_TRASHED_DEL_MYMSG_MONTH_LIMIT";

    public final static String HOUSE_KEEP_ACCBAL_MONTH_LIMIT_PROPERTY_NAME = "HOUSE_KEEP_ACCBAL_MONTH_LIMIT";

    public final static String DEFAULT_MNOT_EXPIRY_TIME_PROPERTY_NAME = "MNOT_EXPIRY_TIME";
    public final static String DEFAULT_MNOT_SOURCE_ID_PROPERTY_NAME = "MNOT_SOURCE_ID";

    public static final String SERVER_ID_PROPERTY_NAME = "SERVER_ID";

    public static final String MAINT_BILL_REQ_RECIPIENT_APP_ID_PROPERTY_NAME = "MAINT_BILL_REQ_RECIPIENT_APP_ID";
    public static final String MAINT_BILL_REQ_SENDER_APP_TYPE_PROPERTY_NAME = "MAINT_BILL_REQ_SENDER_APP_TYPE";
    public static final String MAINT_BILL_REQ_RECIPIENT_APP_TYPE_PROPERTY_NAME = "MAINT_BILL_REQ_RECIPIENT_APP_TYPE";
    public final static String MAINT_BILL_SINGLE_PULL_CALL_LIMIT_PROPERTY = "MAINT_BILL_SINGLE_PULL_CALL_LIMIT";
    public final static String MAINT_BILL_LOCK_JOB_TRY_LIMIT_PROPERTY = "MAINT_BILL_LOCK_JOB_TRY_LIMIT";
    public final static String MAINT_BILL_LOCK_JOB_SLEEP_TIME_PROPERTY = "MAINT_BILL_LOCK_JOB_SLEEP_TIME";

    public final static String BILLCENTER_BCPTF_CUTOFF_ECHQ_PROPERTY_NAME = "BILLCENTER_BCPTF_CUTOFF_ECHQ";

    public final static String IAS_IDP_ID_PROPERTY_NAME = "IAS_IDP_ID";
    public final static String MYGOV_PORTAL_ID_PROPERTY_NAME = "MYGOV_PORTAL_ID";
    public final static String MYGOV_SP_ID_PROPERTY_NAME = "MYGOV_SP_ID";
    public final static String MYGOV_CLIENT_ID_PROPERTY_NAME = "MYGOV_CLIENT_ID";
    public final static String IAS_GET_NOTI_ID_END_POINT_PROPERTY_NAME = "IAS_GET_NOTI_ID_END_POINT";
    public final static String IAS_SEND_NOTI_END_POINT_PROPERTY_NAME = "IAS_SEND_NOTI_END_POINT";
    public final static String IAS_GET_NOTI_RESULT_END_POINT_PROPERTY_NAME = "IAS_GET_NOTI_RESULT_END_POINT";

    public final static String IAS_SWITCH_NOTI_ID_BY_HKID_END_POINT = "IAS_SWITCH_NOTI_ID_BY_HKID_END_POINT";
    public final static String IAS_PUSH_NOTI_END_POINT = "IAS_PUSH_NOTI_END_POINT";

    public final static String IAS_ES_APP_SUFFIX_TAG_NAME_PROPERTY_NAME = "IAS_ES_APP_SUFFIX_TAG_NAME";
    public final static String MAINT_MSG_IAS_MSG_SUBJ_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_MSG_SUBJ_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_MSG_SUBJ_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_MSG_SUBJ_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_MSG_CONTENT_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_MSG_CONTENT_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_MSG_CONTENT_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_MSG_CONTENT_CHI_SIZE_LIMIT";

    public final static String MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_APPLICATION_SUBJ_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_APPLICATION_SUBJ_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_APPLICATION_SUBJ_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_APPLICATION_SUBJ_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_APPLICATION_CONTENT_ENG_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_APPLICATION_CONTENT_ENG_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_APPLICATION_CONTENT_CHI_SIZE_LIMIT_PROPERTY_NAME = "MAINT_MSG_IAS_APPLICATION_CONTENT_CHI_SIZE_LIMIT";
    public final static String MAINT_MSG_IAS_APPLICATION_STATUS_LIST_PROPERTY_NAME = "MAINT_MSG_IAS_APPLICATION_STATUS_LIST";

    public final static String IAS_MSG_PROCESS_BATCH_LIMIT_PROPERTY_NAME = "IAS_MSG_PROCESS_BATCH_LIMIT";
    public final static String IAS_ASSO_JOB_PROCESS_BATCH_LIMIT_PROPERTY_NAME = "IAS_ASSO_JOB_PROCESS_BATCH_LIMIT";
    public final static String IAS_GET_NOTI_ID_BATCH_LIMIT_PROPERTY_NAME = "IAS_GET_NOTI_ID_BATCH_LIMIT";
    public final static String IAS_SEND_NOTI_BATCH_LIMIT_PROPERTY_NAME = "IAS_SEND_NOTI_BATCH_LIMIT";

    public final static String GET_IAS_NOTI_RESULT_DAY_LIMIT_PROPERTY_NAME = "GET_IAS_NOTI_RESULT_DAY_LIMIT";

    public final static String GET_IAS_NOTI_RESULT_TIME_TO_LIVE_DAY_PROPERTY_NAME = "GET_IAS_NOTI_RESULT_TIME_TO_LIVE_DAY";

    public final static String GET_IAS_NOTI_RESULT_SIZE_LIMIT_PROPERTY_NAME = "GET_IAS_NOTI_RESULT_SIZE_LIMIT";
    public final static String IAS_WELCOME_MSG_TEMPLATE_ID_PROPERTY_NAME = "IAS_WELCOME_MSG_TEMPLATE_ID";
    public final static String IAS_WELCOME_MSG_TEMPLATE_VERSION_PROPERTY_NAME = "IAS_WELCOME_MSG_TEMPLATE_VERSION";
    public final static String IAS_WELCOME_MSG_TEMPLATE_SP_ID_PROPERTY_NAME = "IAS_WELCOME_MSG_TEMPLATE_SP_ID";
    public final static String IAS_WELCOME_MSG_TEMPLATE_SP_TAG_PROPERTY_NAME = "IAS_WELCOME_MSG_TEMPLATE_SP_TAG";
    public final static String IAS_MSG_HOUSEKEEP_RETENTION_MONTHS_PROPERTY_NAME = "IAS_MSG_HOUSEKEEP_RETENTION_MONTHS";

    public final static String IAS_TODO_ITEM_HOUSEKEEP_RETENTION_MONTHS_PROPERTY_NAME = "IAS_TODO_ITEM_HOUSEKEEP_RETENTION_MONTHS";

    public final static String IAS_APPLICATION_HOUSEKEEP_RETENTION_MONTHS_PROPERTY_NAME = "IAS_APPLICATION_HOUSEKEEP_RETENTION_MONTHS";

    public final static String IAS_MSG_REQ_RECIPIENT_APP_ID_PROPERTY_NAME = "IAS_MSG_REQ_RECIPIENT_APP_ID";
    public final static String IAS_MSG_REQ_RECIPIENT_APP_TYPE_PROPERTY_NAME = "IAS_MSG_REQ_RECIPIENT_APP_TYPE";
    public final static String IAS_MSG_REQ_SENDER_APP_TYPE_PROPERTY_NAME = "IAS_MSG_REQ_SENDER_APP_TYPE";
    public final static String IAS_MSG_SINGLE_PULL_CALL_LIMIT_PER_BD_PROPERTY = "IAS_MSG_SINGLE_PULL_CALL_LIMIT_PER_BD";
    public final static String IAS_MSG_APP_ID_TRANSFORM_LIST_PROPERTY_NAME = "IAS_MSG_APP_ID_TRANSFORM_LIST";

    public final static String CMC_MESSAGE_ENCRYPT_KEY_STORE_ID_PROPERTY_NAME = "CMC_MESSAGE_ENCRYPT_KEY_STORE_ID";

    public final static String IAS_DEREGISTER_USER_DELETE_MSG_LIMIT = "IAS_DEREGISTER_USER_DELETE_MSG_LIMIT";
    public final static String IAS_UNCONSENT_DELETE_TO_DO_ITEM_LIMIT = "IAS_UNCONSENT_DELETE_TO_DO_ITEM_LIMIT";
    public final static String IAS_UNCONSENT_DELETE_APPLICATION_LIMIT = "IAS_UNCONSENT_DELETE_APPLICATION_LIMIT";

    public final static String HKID_ENCRYPT_PASSPHRASE_ID_PROPERTY_NAME = "HKID_ENCRYPT_PASSPHRASE_ID";
    public final static String HKID_ENCRYPT_PASSPHRASE_USAGE_PROPERTY_NAME = "HKID_ENCRYPT_PASSPHRASE_USAGE";

    public static final String CMC_TO_DCI_CMC_APP_ID_MAP_PROPERTY_NAME = "CMC_TO_DCI_CMC_APP_ID_MAP";

    public static final String CMC_CORE_CERT_FILE_NAME_P12 = "CMC_CORE_CERT_FILE_NAME_P12";

    public static final String PULL_ACK_RECIPIENT_APP_ID_PROPERTY_NAME = "PULL_ACK_RECIPIENT_APP_ID";
    public static final String PULL_ACK_RECIPIENT_APP_TYPE_PROPERTY_NAME = "PULL_ACK_RECIPIENT_APP_TYPE";
    public static final String ASYN_MSG_SOAP_ACTION_PROPERTY_NAME = "ASYN_MSG_SOAP_ACTION";

}
