# ######### EXPIRING KEY/CERT ALERT JOB ######### 
#This property sets the number of days prior to the valid 
#end of keys/certs to be included for an alert warning.
EXPIRING_KEY_CERT_ALERT_DAYS = 10

#This property set the first run time of the expiring key/cert alert
#after server has been restarted.  The display format is HH24:MI. eg. 23:59
EXPIRING_KEY_CERT_ALERT_FIRST_RUN_TIME_HH24_MI = 12:25

#This property set the number of times the job is executed in a day, 
#since the time given in EXPIRING_KEY_CERT_PRE_ALERT_FIRST_RUN_TIME_HH24_MI.
EXPIRING_KEY_CERT_ALERT_RUNS_PER_DAY = 24
# ###################################################


# Other properties

DEFAULT_PASSWORD_BASED_ENCRYPT_ALGORITHM = PBKDF2WithHmacSHA256
# DEFAULT_PASSWORD_BASED_ENCRYPT_ALGORITHM = PBEWithSHA1AndDESede


# DEFAULT_PASSWORD_BASED_ENCRYPT_SALT=Use a cryptographically secure random salt of at least 16 bytes

DEFAULT_HASH_ALGORITHM = SHA256
# DEFAULT_CIPHER_ALGORITHM = RSA/ECB/OAEPWithSHA-256AndMGF1Padding
DEFAULT_CIPHER_ALGORITHM=RSA/NONE/PKCS1PADDING

#DEFAULT_PASSWORD_BASED_ENCRYPT_ITERATIONS=The iteration count should meet individual B/Ds' security requirements, typically at least 10,000.
#DEFAULT_PASSWORD_BASED_ENCRYPT_CIPHER_ALGORITHM=AES/GCM/NoPadding

# Parameters for XML signature
# DEFAULT_XML_SIGNATURE_ALGORITHM_URI=http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
# DEFAULT_XML_HASH_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#sha256
DEFAULT_XML_SIGNATURE_ALGORITHM_URI=http://www.w3.org/2000/09/xmldsig#rsa-sha1
DEFAULT_XML_HASH_ALGORITHM_URI=http://www.w3.org/2000/09/xmldsig#sha1

# Parameters for XML encryption (AES256 bit)
#DEFAULT_XML_DATA_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#aes256-cbc
#DEFAULT_XML_DATA_ENCRYPTION_ALGORITHM_NAME=aes
#DEFAULT_XML_DATA_ENCRYPTION_KEY_SIZE=256
#DEFAULT_XML_KEY_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
#DEFAULT_XML_KEY_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#rsa-1_5


# Parameters for XML encryption (AES128 bit)
DEFAULT_XML_DATA_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#aes128-cbc
DEFAULT_XML_DATA_ENCRYPTION_ALGORITHM_NAME=aes
DEFAULT_XML_DATA_ENCRYPTION_KEY_SIZE=128
DEFAULT_XML_KEY_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
#DEFAULT_XML_KEY_ENCRYPTION_ALGORITHM_URI=http://www.w3.org/2001/04/xmlenc#rsa-1_5




MASTER_KEY_STORE_TYPE = jks
MASTER_KEY_LOCATION = /bd-ogcmr/uat/cmc/cmc-core/config/keyservice/master_keystore_uat_cmc_ogcmr.jks
MASTER_KEY_REAL_ALIAS = master_key_test_cmc_ogcmr_alias
SUPPORTED_KEY_STORE_TYPES = JKS, PKCS12, NCIPHER.SWORLD

CRYPTOGRAPHIC_MESSAGE_SYNTAX_PROVIDER = BC
REFRESH_INTERVAL_MILLIS = 60000
KEY_CACHEABLE=1