status = warn
name = BatchJobConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d [%p] [%c] (%t) %m%n

appender.file.type = File
appender.file.name = BatchJobLog
appender.file.fileName = /bd-ogcmr/prd/cmc/cmc-core/script/log/batchjob.log
appender.file.append = true
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d [%p] [%c] (%t) %m%n

appender.noncritical.type = File
appender.noncritical.name = NonCriticalLog
appender.noncritical.fileName = /bd-ogcmr/prd/cmc/cmc-core/script/log/batchjob.log
appender.noncritical.append = true
appender.noncritical.layout.type = PatternLayout
appender.noncritical.layout.pattern = %d [NON CRITICAL] [%c] (%t) %m%n

logger.xnio.name = org.xnio
logger.xnio.level = info
logger.xnio.additivity = false
logger.xnio.appenderRefs = noncritical
logger.xnio.appenderRef.noncritical.ref = NonCriticalLog

rootLogger.level = info
rootLogger.appenderRefs = stdout, file
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = BatchJobLog
