HTTPS_APPLICATION.1=https://ttgd-xmlfw.egisdctr.hksarg:8443
HTTPS_APPLICATION.2=https://ttgd-xmlfw.egisdctr.hksarg:8443

HTTPS_CLIENT_AUTH_APPLICATION.1=https://ttgd-xmlfw.egisdctr.hksarg:8444
HTTPS_CLIENT_AUTH_APPLICATION.2=https://ttgd-xmlfw.egisdctr.hksarg:8444

HTTPS_CLIENT_AUTH_RESTFUL_APPLICATION.1=https://ttgd-xmlfw.egisdctr.hksarg:8444
HTTPS_CLIENT_AUTH_RESTFUL_APPLICATION.2=https://ttgd-xmlfw.egisdctr.hksarg:8444

WSS_APPLICATION.1=https://ttgd-xmlfw.egisdctr.hksarg:8443
WSS_APPLICATION.2=https://ttgd-xmlfw.egisdctr.hksarg:8443

SSL_APPLICATION.1=https://ttgd-xmlfw.egisdctr.hksarg:8444
SSL_APPLICATION.2=https://ttgd-xmlfw.egisdctr.hksarg:8444
