//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for Action.ST</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="Action.ST">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="New"/>
 *     <enumeration value="Delete"/>
 *     <enumeration value="Replace"/>
 *     <enumeration value="MarkComplete"/>
 *     <enumeration value="Update"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Action.ST", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
@XmlEnum
public enum ActionST {

    @XmlEnumValue("New")
    NEW("New"),
    @XmlEnumValue("Delete")
    DELETE("Delete"),
    @XmlEnumValue("Replace")
    REPLACE("Replace"),
    @XmlEnumValue("MarkComplete")
    MARK_COMPLETE("MarkComplete"),
    @XmlEnumValue("Update")
    UPDATE("Update");
    private final String value;

    ActionST(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ActionST fromValue(String v) {
        for (ActionST c: ActionST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
