//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaintainMessageResponse complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MaintainMessageResponse">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="ResultMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MessageResponse" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd}MessageResponse.CT" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlRootElement(name = "MaintainMessageResponse", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaintainMessageResponse", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", propOrder = {
    "resultCode",
    "resultMessage",
    "messageResponse"
})
public class MaintainMessageResponse {

    @XmlElement(name = "ResultCode", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", required = true)
    protected String resultCode;
    @XmlElement(name = "ResultMessage", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected String resultMessage;
    @XmlElement(name = "MessageResponse", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected List<MessageResponseCT> messageResponse;

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultMessage() {
        return resultMessage;
    }

    /**
     * Sets the value of the resultMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultMessage(String value) {
        this.resultMessage = value;
    }

    /**
     * Gets the value of the messageResponse property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageResponse property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMessageResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageResponseCT }
     * </p>
     * 
     * 
     * @return
     *     The value of the messageResponse property.
     */
    public List<MessageResponseCT> getMessageResponse() {
        if (messageResponse == null) {
            messageResponse = new ArrayList<MessageResponseCT>();
        }
        return this.messageResponse;
    }

}
