//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageRequest.CT complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MessageRequest.CT">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="PortalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="EMessage" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}EMessage.CT" minOccurs="0"/>
 *         <element name="ToDoItem" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}ToDoItem.CT" minOccurs="0"/>
 *         <element name="Application" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}Application.CT" minOccurs="0"/>
 *         <element name="MetaData" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}MetaData.CT" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageRequest.CT", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", propOrder = {
    "portalID",
    "eMessage",
    "toDoItem",
    "application",
    "metaData"
})
public class MessageRequestCT {

    @XmlElement(name = "PortalID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected String portalID;
    @XmlElement(name = "EMessage", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected EMessageCT eMessage;
    @XmlElement(name = "ToDoItem", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected ToDoItemCT toDoItem;
    @XmlElement(name = "Application", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected ApplicationCT application;
    @XmlElement(name = "MetaData", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected List<MetaDataCT> metaData;

    /**
     * Gets the value of the portalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalID() {
        return portalID;
    }

    /**
     * Sets the value of the portalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalID(String value) {
        this.portalID = value;
    }

    /**
     * Gets the value of the eMessage property.
     * 
     * @return
     *     possible object is
     *     {@link EMessageCT }
     *     
     */
    public EMessageCT getEMessage() {
        return eMessage;
    }

    /**
     * Sets the value of the eMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMessageCT }
     *     
     */
    public void setEMessage(EMessageCT value) {
        this.eMessage = value;
    }

    /**
     * Gets the value of the toDoItem property.
     * 
     * @return
     *     possible object is
     *     {@link ToDoItemCT }
     *     
     */
    public ToDoItemCT getToDoItem() {
        return toDoItem;
    }

    /**
     * Sets the value of the toDoItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToDoItemCT }
     *     
     */
    public void setToDoItem(ToDoItemCT value) {
        this.toDoItem = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationCT }
     *     
     */
    public ApplicationCT getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationCT }
     *     
     */
    public void setApplication(ApplicationCT value) {
        this.application = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metaData property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaDataCT }
     * </p>
     * 
     * 
     * @return
     *     The value of the metaData property.
     */
    public List<MetaDataCT> getMetaData() {
        if (metaData == null) {
            metaData = new ArrayList<MetaDataCT>();
        }
        return this.metaData;
    }

}
