//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetaData.CT complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MetaData.CT">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DataContentEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="DataContentTC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="DataContentSC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Recipient" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}Recipient.CT" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetaData.CT", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", propOrder = {
    "dataContentEN",
    "dataContentTC",
    "dataContentSC",
    "recipient"
})
public class MetaDataCT {

    @XmlElement(name = "DataContentEN", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected String dataContentEN;
    @XmlElement(name = "DataContentTC", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String dataContentTC;
    @XmlElement(name = "DataContentSC", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String dataContentSC;
    @XmlElement(name = "Recipient", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected List<RecipientCT> recipient;

    /**
     * Gets the value of the dataContentEN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContentEN() {
        return dataContentEN;
    }

    /**
     * Sets the value of the dataContentEN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContentEN(String value) {
        this.dataContentEN = value;
    }

    /**
     * Gets the value of the dataContentTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContentTC() {
        return dataContentTC;
    }

    /**
     * Sets the value of the dataContentTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContentTC(String value) {
        this.dataContentTC = value;
    }

    /**
     * Gets the value of the dataContentSC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContentSC() {
        return dataContentSC;
    }

    /**
     * Sets the value of the dataContentSC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContentSC(String value) {
        this.dataContentSC = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipient property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecipientCT }
     * </p>
     * 
     * 
     * @return
     *     The value of the recipient property.
     */
    public List<RecipientCT> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<RecipientCT>();
        }
        return this.recipient;
    }

}
