//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hk.gov.dpo.mars_cmc.cmc.jaxb.maintainmessage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MaintainMessageRequest }
     * 
     * @return
     *     the new instance of {@link MaintainMessageRequest }
     */
    public MaintainMessageRequest createMaintainMessageRequest() {
        return new MaintainMessageRequest();
    }

    /**
     * Create an instance of {@link MessageRequestCT }
     * 
     * @return
     *     the new instance of {@link MessageRequestCT }
     */
    public MessageRequestCT createMessageRequestCT() {
        return new MessageRequestCT();
    }

    /**
     * Create an instance of {@link MetaDataCT }
     * 
     * @return
     *     the new instance of {@link MetaDataCT }
     */
    public MetaDataCT createMetaDataCT() {
        return new MetaDataCT();
    }

    /**
     * Create an instance of {@link RecipientCT }
     * 
     * @return
     *     the new instance of {@link RecipientCT }
     */
    public RecipientCT createRecipientCT() {
        return new RecipientCT();
    }

    /**
     * Create an instance of {@link EMessageCT }
     * 
     * @return
     *     the new instance of {@link EMessageCT }
     */
    public EMessageCT createEMessageCT() {
        return new EMessageCT();
    }

    /**
     * Create an instance of {@link ToDoItemCT }
     * 
     * @return
     *     the new instance of {@link ToDoItemCT }
     */
    public ToDoItemCT createToDoItemCT() {
        return new ToDoItemCT();
    }

    /**
     * Create an instance of {@link ApplicationCT }
     * 
     * @return
     *     the new instance of {@link ApplicationCT }
     */
    public ApplicationCT createApplicationCT() {
        return new ApplicationCT();
    }

}
