# CMC database data source name
DB_CONNECTION_DS_NAME_1=java:jboss/jdbc/CMCDataSource
DB_CONNECTION_DS_NAME_2=java:jboss/jdbc/CMCDataSource

SERVER_SEQUENCE_PREFIX=W
SERVER_SEQUENCE_PREFIX_2=T

SERVER_ID=1

# MyGov Machine Gen Seguence Prefix
MYSQL_SELFGEN_SEQ_PREFIX=WCC1
DB=MYSQL

AUTH_TYPE=SSL_CLIENT_X509_CERTIFICATE

# define the application to be used in proximity.properties
DEFAULT_APPLICATION=SSL_APPLICATION
RETRY_ON_EXCEPTION_FLAG=Y
PROXIMITY_CONFIG_FILE=/bd-ogcmr/bduat/cmc/cmc-core/config/proximity.properties

KEY_STORE_FILE_NAME=/bd-ogcmr/bduat/cmc/cmc-core/cert/cmc_be_bd.marsdctr.hksarg.ca256.keystore.p12
KEY_STORE_PASSWORD=changeit
KEY_STORE_TYPE=pkcs12

# SUN JRE
SECURE_SOCKET_FACTORY=hk.gov.spica_scopes.common.utils.SunJSSESocketFactory
TRUST_STORE_PROVIDER=SUN

TRUST_STORE_FILE_NAME=/bd-ogcmr/bduat/java/customise/cacerts-override.jks
TRUST_STORE_PASSWORD=changeit
TRUST_STORE_TYPE=jks

ASYN_MSG_END_POINT=https://EGIS:9444/messaging/ssl/soap/ogcio.ogcmr.app001-ogcio.egis.msg001-AsynMsg
ASYN_MSG_SOAP_ACTION=AsyncMsgService

SING_PULL_END_POINT=https://EGIS:9444/messaging/ssl/soap/ogcio.ogcmr.app001-ogcio.egis.msg001-SingPull
SING_PULL_SOAP_ACTION=SinglePullService

BAT_PULL_END_POINT=https://EGIS:9444/messaging/ssl/soap/ogcio.ogcmr.app001-ogcio.egis.msg001-BatPull
BAT_PULL_SOAP_ACTION=BatchPullService

PULL_ACK_END_POINT=https://EGIS:9444/messaging/ssl/soap/ogcio.ogcmr.app001-ogcio.egis.msg001-PullAck
PULL_ACK_SOAP_ACTION=PullAckService

NOTI_SENDER_END_POINT=https://EGIS:9444/messaging/ssl/soap/ogcio.ogcmr.app001-ogcio.egis.nt001-NotiSender
NOTI_SENDER_SOAP_ACTION=NotificationSender

###############################################################################
# EGIS Message Store & Forward Setting; Maintain Message
###############################################################################
MAINT_MSG_REQ_RECIPIENT_APP_ID=ogcio.ogcmr.app212
MAINT_MSG_REQ_SENDER_APP_ID=ogcio.ogcmr.app211

MAINT_MSG_REQ_SENDER_APP_TYPE=MAINT_MSG
MAINT_MSG_REQ_RECIPIENT_APP_TYPE=MAINT_MSG

MAINT_MSG_SINGLE_PULL_CALL_LIMIT=10
MAINT_MSG_SUBJ_SIZE_LIMIT=1024
MAINT_MSG_CONTENT_SIZE_LIMIT=20480


###############################################################################
# Properties for CMC System Parameter Reload Time
# 1000 = 1 sec
# default = 3600000 (1 hr)
###############################################################################
LOAD_CMC_SYS_PARAM_MILLIS=600000


###############################################################################
# Report Properties
###############################################################################
#REPORTFW_LOCAL_EJB_JNDI_NAME=cmc/FwReportSessionEJB/local
REPORTFW_LOCAL_EJB_JNDI_NAME=java:global/cmc/reportfw_ejb3/FwReportSessionEJB!hk.gov.ogcio.mars_cmc.reportfw.appserver.ejb.session.IFwReportSessionBMLocal
REPORTFW_HPFW_CONNECTION=getHPFW_Connection
JASPER_REPORT_PATH=/bd-ogcmr/bduat/cmc/cmc-core/report/jasper


###############################################################################
# CMC HEALTH CHECK EMAIL
###############################################################################
CMC_HEALTH_CHECK_REPORT_DIR=/bd-ogcmr/bduat/cmc/cmc-core/script/cmc-health-check-report
CMC_HEALTH_CHECK_REPORT_FILE_NAME=cmcHealthCheckReport

CMC_HEALTH_CHECK_EMAIL_CHARSET=UTF-8
CMC_HEALTH_CHECK_EMAIL_CONTENT_TYPE=text/plain
CMC_HEALTH_CHECK_EMAIL_SUBJECT=CMC Health Check (DCI-BDUAT)
CMC_HEALTH_CHECK_EMAILS=ericskleung@digitalpolicy.gov.hk,rkcliawu@digitalpolicy.gov.hk
HEALTH_CHECK_KEY_STORE_FILE_NAME=/bd-ogcmr/bduat/cmc/cmc-core/cert/cmc_healthcheck_bd.marsdctr.hksarg.ca256.keystore.p12
CMC_HOUSEKEEP_HEALTH_CHECK_REPORT_FILE_NAME=cmcHousekeepHealthCheckReport


LOG_CHECK_KEY_STORE_FILE_NAME=/bd-ogcmr/bduat/cmc/cmc-core/cert/cmc_healthcheck_bd.marsdctr.hksarg.ca256.keystore.p12
CMC_LOG_CHECK_REPORT_DIR=/bd-ogcmr/bduat/cmc/cmc-core/script/cmc-health-check-report
CMC_LOG_CHECK_EMAIL_CHARSET=UTF-8
CMC_LOG_CHECK_EMAIL_CONTENT_TYPE=text/plain
CMC_LOG_CHECK_EMAIL_SUBJECT=CMC Log Check (DCI-BDUAT)
CMC_LOG_CHECK_EMAIL_CONTENT_FILE_PREFIX=cmcConsolErrorCount_ecs-ttcp-cmcapp03_,cmcConsolErrorCount_ecs-ttcp-cmcapp04_
CMC_LOG_CHECK_EMAIL_ATTACHMENT_FILE_PREFIX=cmcConsolErrorDetail_ecs-ttcp-cmcapp03_,cmcConsolErrorDetail_ecs-ttcp-cmcapp04_
CMC_LOG_CHECK_FILE_EXTENSION=.txt
CMC_LOG_CHECK_EMAIL_ATTH_SIZE_LIMIT=1048576
CMC_LOG_CHECK_EMAILS=ericskleung@digitalpolicy.gov.hk,pskmok@digitalpolicy.gov.hk,rkcliawu@digitalpolicy.gov.hk

JOB_CONTROL_MAINT_MSG=JOB_CONTROL_MAINT_MSG
JOB_CONTROL_MAINT_MSG_TIMEOUT_CHECK_NEEDED=N
JOB_CONTROL_MAINT_MSG_TIMEOUT_MINS=60

# SYNC JOB HEALTH CHECK
CMC_LOCK_TIME_THRESHOLD_IN_HOUR=2


###############################################################################
# Housekeeping Setting
###############################################################################
IAS_MSG_HOUSEKEEP_RETENTION_MONTHS=24
IAS_TODO_ITEM_HOUSEKEEP_RETENTION_MONTHS=6
IAS_APPLICATION_HOUSEKEEP_RETENTION_MONTHS=6
HOUSE_KEEP_BATCH_SIZE=1000
HOUSE_KEEP_DEL_NON_USER_TBL_MONTH_LIMIT=24
JOB_CONTROL_HOUSE_KEEP=JOB_CONTROL_HOUSE_KEEP
JOB_CONTROL_HOUSE_KEEP_TIMEOUT_CHECK_NEEDED=N
JOB_CONTROL_HOUSE_KEEP_TIMEOUT_MINS=60
HOUSE_KEEP_ACCBAL_MONTH_LIMIT=24
HOUSE_KEEP_DEL_NON_USER_TBL_MONTH_LIMIT=47
HOUSE_KEEP_DEL_ARCHIVE_INDEX_TBL_MONTH_LIMIT=60
HOUSE_KEEP_DEL_HIST_TBL_BATCH_SIZE=5000
HOUSE_KEEP_NO_OF_BATCH=40


###############################################################################
# FW Batch checking
###############################################################################
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcHealthCheckJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcHistoryTableHealthCheck_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcLogCheckJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcResetSyncJobLock_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcSetSyncJobEnableFlag_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcSyncJobHealthCheck_ENABLED=Y

FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcIasQueryWelcomeMsgJob_ENABLED=Y

FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcSendIasNotiJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcSendIasToDoItemNotiJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcSendIasApplicationNotiJob_ENABLED=Y

FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcQueryIasNotiResultJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcQueryIasToDoItemNotiResultJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcQueryIasApplicationResultJob_ENABLED=Y

FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcDeleteDeRegIasUserMsgJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcDeleteUnconsentIasToDoItemJob_ENABLED=Y
FW_BATCH_IMPL_CLASS_hk.gov.cmc.batch.CmcDeleteUnconsentIasApplicationJob_ENABLED=Y


###########################
# New report framework for ADMSYS
##########################
JOB_CONTROL_GEN_ADMIN_REPORT=JOB_CONTROL_GEN_ADMIN_REPORT
JOB_CONTROL_REGEN_ADMIN_BATCH_REPORT=JOB_CONTROL_REGEN_ADMIN_BATCH_REPORT


###########################
# iAM Smart Message
###########################
IAS_IDP_ID=iamsmart
MYGOV_SP_ID=MARS
MYGOV_CLIENT_ID=fe6583bacbec4727a5dc7c38ca229f62
IAS_ES_APP_SUFFIX_TAG_NAME=ESLINKSUFFIX
IAS_MSG_PROCESS_BATCH_LIMIT=1000
IAS_GET_NOTI_ID_BATCH_LIMIT=500
IAS_SEND_NOTI_BATCH_LIMIT=1000
MAINT_MSG_IAS_MSG_SUBJ_ENG_SIZE_LIMIT=255
MAINT_MSG_IAS_MSG_SUBJ_CHI_SIZE_LIMIT=255
MAINT_MSG_IAS_MSG_CONTENT_ENG_SIZE_LIMIT=20480
MAINT_MSG_IAS_MSG_CONTENT_CHI_SIZE_LIMIT=20480
JOB_CONTROL_SEND_IAS_NOTI=JOB_CONTROL_SEND_IAS_NOTI
JOB_CONTROL_GET_IAS_NOTI_RESULT=JOB_CONTROL_GET_IAS_NOTI_RESULT
JOB_CONTROL_DELETE_DEREG_IAS_USER_MSG=JOB_CONTROL_DELETE_DEREG_IAS_USER_MSG
IAS_GET_NOTI_ID_END_POINT=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/noti/getNotificationID
IAS_SEND_NOTI_END_POINT=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/noti/sendNotification
IAS_GET_NOTI_RESULT_END_POINT=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/noti/queryStatus
IAS_DEREGISTER_USER_DELETE_MSG_LIMIT=1000
EID_ENC_DEC_PRIVATE_KEY_FRIENDLY_ALIAS=EID_ENC_DEC_PRIVATE_KEY
EID_CLIENT_ID=fe6583bacbec4727a5dc7c38ca229f62
EID_CLIENT_SECRET_ID=EID_CLIENT_SECRET_ID
EID_CLIENT_SECRET_USAGE_TYPE=EID
EID_SYM_ENC_KEY_REQUEST_URL=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/security/getKey
EID_PROXY_SERVER=172.16.67.21
EID_PROXY_PORT=80
EID_SSL_TRUST_STORE_PATH=/bd-ogcmr/bduat/cmc/cmc-core/cert/truststore_iamsmart_ssl.jks
EID_CERT_CN_NAME=apigw-isit.cloud.staging-eid.gov.hk

GET_IAS_NOTI_RESULT_TIME_TO_LIVE_DAY=0
GET_IAS_NOTI_RESULT_DAY_LIMIT=7
GET_IAS_NOTI_RESULT_SIZE_LIMIT=10000

# iAM Smart association queue
MYGOV_PORTAL_ID=mygovhk
IAS_ASSO_JOB_PROCESS_BATCH_LIMIT=10000
IAS_WELCOME_MSG_TEMPLATE_ID=IAS_WELCOME_MSG
IAS_WELCOME_MSG_TEMPLATE_VERSION=1
IAS_WELCOME_MSG_TEMPLATE_SP_ID=MARS
IAS_WELCOME_MSG_TEMPLATE_SP_TAG=<SP_NAME>

#iAM Smart non-vip BD send welcome message config
IAS_MSG_REQ_RECIPIENT_APP_ID=ogcio.ogcmr.app212
IAS_MSG_REQ_RECIPIENT_APP_TYPE=IAS_MSG
IAS_MSG_REQ_SENDER_APP_TYPE=IAS_MSG
IAS_MSG_SINGLE_PULL_CALL_LIMIT_PER_BD=10
JOB_CONTROL_IAS_MSG_WELCOME_MSG=JOB_CONTROL_IAS_MSG_WELCOME_MSG
IAS_MSG_APP_ID_TRANSFORM_LIST=ogcio.mrird.app102:ogcio.ogcmr.app111,ogcio.ogcmr.app111:ogcio.ogcmr.app111

# CMC message encryption
CMC_MESSAGE_ENCRYPT_KEY_STORE_ID=CMC_MESSAGE_ENCRYPT_KEY_4

CONFIG_RELOAD_VALID_IP=10.123.56.7,10.123.56.8
EID_REVOKE_SYM_ENC_KEY_REQUEST_URL=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/security/revokeKey


JOB_CONTROL_SEND_IAS_TO_TO_ITEM_NOTI=JOB_CONTROL_SEND_IAS_TO_TO_ITEM_NOTI
JOB_CONTROL_GET_IAS_TO_DO_ITEM_NOTI_RESULT=JOB_CONTROL_GET_IAS_TO_DO_ITEM_NOTI_RESULT


JOB_CONTROL_SEND_IAS_APPLICATION_NOTI=JOB_CONTROL_SEND_IAS_APPLICATION_NOTI
JOB_CONTROL_GET_IAS_APPLICATION_NOTI_RESULT=JOB_CONTROL_GET_IAS_APPLICATION_NOTI_RESULT

JOB_CONTROL_UNCONSENT_DELETE_TO_DO_ITEM=JOB_CONTROL_UNCONSENT_DELETE_TO_DO_ITEM
IAS_UNCONSENT_DELETE_TO_DO_ITEM_LIMIT=1000

JOB_CONTROL_UNCONSENT_DELETE_APPLICATION=JOB_CONTROL_UNCONSENT_DELETE_APPLICATION
IAS_UNCONSENT_DELETE_APPLICATION_LIMIT=1000

IAS_SWITCH_NOTI_ID_BY_HKID_END_POINT=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/msg/switchNotificationID
IAS_PUSH_NOTI_END_POINT=https://apigw-isit.cloud.staging-eid.gov.hk/api/v1/noti/pushNotification

MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_ENG_SIZE_LIMIT=255
MAINT_MSG_IAS_TO_DO_ITEM_SUBJ_CHI_SIZE_LIMIT=255
MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_ENG_SIZE_LIMIT=20480
MAINT_MSG_IAS_TO_DO_ITEM_CONTENT_CHI_SIZE_LIMIT=20480
MAINT_MSG_IAS_APPLICATION_SUBJ_ENG_SIZE_LIMIT=255
MAINT_MSG_IAS_APPLICATION_SUBJ_CHI_SIZE_LIMIT=255
MAINT_MSG_IAS_APPLICATION_CONTENT_ENG_SIZE_LIMIT=20480
MAINT_MSG_IAS_APPLICATION_CONTENT_CHI_SIZE_LIMIT=20480

HKID_ENCRYPT_PASSPHRASE_ID=HKID_ENCRYPT_PASSPHRASE_ID
HKID_ENCRYPT_PASSPHRASE_USAGE=HKID_ENCRYPT_PASSPHRASE_USAGE

TO_DO_ITEM_IMPORTANT_DT_UPPER_LIMIT=365

CMC_TO_DCI_CMC_APP_ID_MAP=ogcio.ogcmr.app212|ogcio.ogcmr.app211