# Root logger option
log4j.rootLogger=INFO, BatchJobLog, stdout

# Direct log messages to a log file
log4j.appender.BatchJobLog=org.apache.log4j.FileAppender
log4j.appender.BatchJobLog.File=/bd-ogcmr/uat/cmc/script/log/batchjob.log
log4j.appender.BatchJobLog.layout=org.apache.log4j.PatternLayout
log4j.appender.BatchJobLog.layout.ConversionPattern=%d [%p] [%c] (%t:%x) %m%n

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d [%p] [%c] (%t:%x) %m%n

# Log WILDFLY EJB client logs as NON CRITICAL
log4j.logger.org.xnio=INFO, nonCriticalLog
log4j.additivity.org.xnio=false

log4j.appender.nonCriticalLog=org.apache.log4j.FileAppender
log4j.appender.nonCriticalLog.File=/bd-ogcmr/uat/cmc/script/log/batchjob.log
log4j.appender.nonCriticalLog.Threshold=INFO
log4j.appender.nonCriticalLog.layout=org.apache.log4j.PatternLayout
log4j.appender.nonCriticalLog.layout.ConversionPattern=%d [NON CRITICAL] [%c] (%t:%x) %m%n
