WSS_APPLICATION.1=https://kpgd-xmlfw.egis.hksarg:8443
WSS_APPLICATION.2=https://spgd-xmlfw.egis.hksarg:8443

SSL_APPLICATION.1=https://kpgd-xmlfw.egis.hksarg:8444
SSL_APPLICATION.2=https://spgd-xmlfw.egis.hksarg:8444
