//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.cmc.jaxb.maintainmessage;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for AppStatus.ST</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="AppStatus.ST">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AR"/>
 *     <enumeration value="UP"/>
 *     <enumeration value="BP"/>
 *     <enumeration value="RJ"/>
 *     <enumeration value="CP"/>
 *     <enumeration value="CA"/>
 *     <enumeration value="AP"/>
 *     <enumeration value="DB"/>
 *     <enumeration value="AL"/>
 *     <enumeration value="PD"/>
 *     <enumeration value="NA"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "AppStatus.ST", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
@XmlEnum
public enum AppStatusST {

    AR,
    UP,
    BP,
    RJ,
    CP,
    CA,
    // CMC-2025-026: Add new Status Codes for Application Status - BEGIN
    AP,
    DB,
    AL,
    PD,
    NA;
    // CMC-2025-026: Add new Status Codes for Application Status - END

    public String value() {
        return name();
    }

    public static AppStatusST fromValue(String v) {
        return valueOf(v);
    }

}
