//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.cmc.jaxb.maintainmessage;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaintainMessageRequest complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MaintainMessageRequest">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="MessageRequest" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}MessageRequest.CT" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlRootElement(name = "MaintainMessageRequest", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaintainMessageRequest", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", propOrder = {
    "messageRequest"
})
public class MaintainMessageRequest {

    @XmlElement(name = "MessageRequest", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected List<MessageRequestCT> messageRequest;

    /**
     * Gets the value of the messageRequest property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageRequest property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMessageRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageRequestCT }
     * </p>
     * 
     * 
     * @return
     *     The value of the messageRequest property.
     */
    public List<MessageRequestCT> getMessageRequest() {
        if (messageRequest == null) {
            messageRequest = new ArrayList<MessageRequestCT>();
        }
        return this.messageRequest;
    }

}
