//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.cmc.jaxb.maintainmessage;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageResponse.CT complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MessageResponse.CT">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TranID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="IdpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="RecipientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="TranResultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="TranResultMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AppRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageResponse.CT", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", propOrder = {
    "tranID",
    "idpID",
    "recipientID",
    "tranResultCode",
    "tranResultMessage",
    "appRefNum",
    "msgType"
})
public class MessageResponseCT {

    @XmlElement(name = "TranID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected String tranID;
    @XmlElement(name = "IdpID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", required = true)
    protected String idpID;
    @XmlElement(name = "RecipientID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", required = true)
    protected String recipientID;
    @XmlElement(name = "TranResultCode", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd", required = true)
    protected String tranResultCode;
    @XmlElement(name = "TranResultMessage", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected String tranResultMessage;
    @XmlElement(name = "AppRefNum", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected String appRefNum;
    @XmlElement(name = "MsgType", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageResponse.xsd")
    protected String msgType;

    /**
     * Gets the value of the tranID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranID() {
        return tranID;
    }

    /**
     * Sets the value of the tranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranID(String value) {
        this.tranID = value;
    }

    /**
     * Gets the value of the idpID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdpID() {
        return idpID;
    }

    /**
     * Sets the value of the idpID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdpID(String value) {
        this.idpID = value;
    }

    /**
     * Gets the value of the recipientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientID() {
        return recipientID;
    }

    /**
     * Sets the value of the recipientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientID(String value) {
        this.recipientID = value;
    }

    /**
     * Gets the value of the tranResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranResultCode() {
        return tranResultCode;
    }

    /**
     * Sets the value of the tranResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranResultCode(String value) {
        this.tranResultCode = value;
    }

    /**
     * Gets the value of the tranResultMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranResultMessage() {
        return tranResultMessage;
    }

    /**
     * Sets the value of the tranResultMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranResultMessage(String value) {
        this.tranResultMessage = value;
    }

    /**
     * Gets the value of the appRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppRefNum() {
        return appRefNum;
    }

    /**
     * Sets the value of the appRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppRefNum(String value) {
        this.appRefNum = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }
}
