//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package hk.gov.cmc.jaxb.maintainmessage;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Recipient.CT complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Recipient.CT">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TranID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="IdpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="RecipientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="AppRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="RecipientIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ItemDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="Action" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}Action.ST" minOccurs="0"/>
 *         <element name="CorrelatedTranID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AppStatus" type="{http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd}AppStatus.ST" minOccurs="0"/>
 *         <element name="AppStatusUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="ContactNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MiscInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Recipient.CT", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", propOrder = {
    "tranID",
    "idpID",
    "recipientID",
    "appRefNum",
    "recipientIDType",
    "itemDate",
    "action",
    "correlatedTranID",
    "appStatus",
    "appStatusUpdateDate",
    "contactNum",
    "contactEmail",
    "miscInfo"
})
public class RecipientCT {

    @XmlElement(name = "TranID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected String tranID;
    @XmlElement(name = "IdpID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected String idpID;
    @XmlElement(name = "RecipientID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd", required = true)
    protected String recipientID;
    @XmlElement(name = "AppRefNum", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String appRefNum;
    @XmlElement(name = "RecipientIDType", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String recipientIDType;
    @XmlElement(name = "ItemDate", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itemDate;
    @XmlElement(name = "Action", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    @XmlSchemaType(name = "string")
    protected ActionST action;
    @XmlElement(name = "CorrelatedTranID", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String correlatedTranID;
    @XmlElement(name = "AppStatus", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    @XmlSchemaType(name = "string")
    protected AppStatusST appStatus;
    @XmlElement(name = "AppStatusUpdateDate", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar appStatusUpdateDate;
    @XmlElement(name = "ContactNum", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String contactNum;
    @XmlElement(name = "ContactEmail", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String contactEmail;
    @XmlElement(name = "MiscInfo", namespace = "http://ws.mygovhk.gov.hk/schema/MaintainMessageRequest.xsd")
    protected String miscInfo;

    /**
     * Gets the value of the tranID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranID() {
        return tranID;
    }

    /**
     * Sets the value of the tranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranID(String value) {
        this.tranID = value;
    }

    /**
     * Gets the value of the idpID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdpID() {
        return idpID;
    }

    /**
     * Sets the value of the idpID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdpID(String value) {
        this.idpID = value;
    }

    /**
     * Gets the value of the recipientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientID() {
        return recipientID;
    }

    /**
     * Sets the value of the recipientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientID(String value) {
        this.recipientID = value;
    }

    /**
     * Gets the value of the appRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppRefNum() {
        return appRefNum;
    }

    /**
     * Sets the value of the appRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppRefNum(String value) {
        this.appRefNum = value;
    }

    /**
     * Gets the value of the recipientIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientIDType() {
        return recipientIDType;
    }

    /**
     * Sets the value of the recipientIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientIDType(String value) {
        this.recipientIDType = value;
    }

    /**
     * Gets the value of the itemDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItemDate() {
        return itemDate;
    }

    /**
     * Sets the value of the itemDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItemDate(XMLGregorianCalendar value) {
        this.itemDate = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionST }
     *     
     */
    public ActionST getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionST }
     *     
     */
    public void setAction(ActionST value) {
        this.action = value;
    }

    /**
     * Gets the value of the correlatedTranID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelatedTranID() {
        return correlatedTranID;
    }

    /**
     * Sets the value of the correlatedTranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelatedTranID(String value) {
        this.correlatedTranID = value;
    }

    /**
     * Gets the value of the appStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AppStatusST }
     *     
     */
    public AppStatusST getAppStatus() {
        return appStatus;
    }

    /**
     * Sets the value of the appStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppStatusST }
     *     
     */
    public void setAppStatus(AppStatusST value) {
        this.appStatus = value;
    }

    /**
     * Gets the value of the appStatusUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppStatusUpdateDate() {
        return appStatusUpdateDate;
    }

    /**
     * Sets the value of the appStatusUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppStatusUpdateDate(XMLGregorianCalendar value) {
        this.appStatusUpdateDate = value;
    }

    /**
     * Gets the value of the contactNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNum() {
        return contactNum;
    }

    /**
     * Sets the value of the contactNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNum(String value) {
        this.contactNum = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the miscInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscInfo() {
        return miscInfo;
    }

    /**
     * Sets the value of the miscInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscInfo(String value) {
        this.miscInfo = value;
    }

}
