# Properties for Quartz -- BEGIN
org.quartz.scheduler.instanceName = RmScheduler
org.quartz.scheduler.instanceId = AUTO
# jboss/wildfly
org.quartz.scheduler.userTransactionURL = java:jboss/UserTransaction
# open liberty
#org.quartz.scheduler.userTransactionURL = jta/usertransaction

org.quartz.scheduler.wrapJobExecutionInUserTransaction = true

# jboss/wildfly
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 10
org.quartz.threadPool.threadPriority = 5

org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource = managedDS
org.quartz.jobStore.nonManagedTXDataSource = nonManagedTXDS

# jboss/wildfly
org.quartz.dataSource.managedDS.jndiURL = java:jboss/jdbc/RMDataSource
org.quartz.dataSource.nonManagedTXDS.jndiURL = java:jboss/jdbc/nonManagedTXDS
# open liberty
#org.quartz.dataSource.managedDS.jndiURL = jdbc/RMDataSource
#org.quartz.dataSource.nonManagedTXDS.jndiURL = jdbc/nonManagedTXDS

org.quartz.plugin.triggHistory.class = org.quartz.plugins.history.LoggingTriggerHistoryPlugin
org.quartz.plugin.shutdownhook.class = org.quartz.plugins.management.ShutdownHookPlugin

# Properties for Quartz -- END

# Properties for spica & scopes -- BEGIN

SERVICE_FACTORY_DATA_SOURCE_NAME = RmDSRef

JUG_ETHERNET_ADDRESS_NAME = 00:01:02:03:04:05

# Properties for SCOPES --  START
RETRY_ON_EXCEPTION_FLAG = Y
PROXIMITY_CONFIG_FILE=/bd-xxx-app/portal/config/proximity.properties
DEFAULT_APPLICATION=HTTPS_APPLICATION
MAX_FILE_SIZE=1000000

RESTART_INTERVAL = 3000000

ASYN_MSG_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-AsynMsg
ASYN_MSG_SOAP_ACTION=AsyncMsgService

BAT_PULL_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-BatPull
BAT_PULL_SOAP_ACTION=BatchPullService

DELV_MSG_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-DelvMsgRetr
DELV_MSG_SOAP_ACTION=DeliveredMessageService

MSG_ENQ_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-MsgEnq
MSG_ENQ_SOAP_ACTION=MessageStatusService

QUE_ENQ_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-QueEnq
QUE_ENQ_SOAP_ACTION=QueueEnquiryService

PULL_ACK_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-PullAck
PULL_ACK_SOAP_ACTION=PullAckService

SING_PULL_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-SingPull
SING_PULL_SOAP_ACTION=SinglePullService

TEST_MSG_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-Test
TEST_MSG_SOAP_ACTION=TestMsgService

GRP_MSG_CONF_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-GrpCfm
GRP_MSG_CONF_SOAP_ACTION=GroupConfirmService

GRP_MSG_CANL_END_POINT=https://<xml_fw_host:port>/messaging/ssl/soap/xxx.yyy.zzz-ogcio.egis.msg001-GrpCnl
GRP_MSG_CANL_SOAP_ACTION=GroupCancelService
# Properties for SCOPES --  END

#if use IBM JDK
#SECURE_SOCKET_FACTORY = hk.gov.gcis.ss.common.utils.IBMJSSESocketFactory
