#
# Properties declaration of users roles for the realm 'ApplicationRealm' which is the default realm
# for application services on a new installation.
#
# This includes the following protocols: remote ejb, remote jndi, web, remote jms
#
# Users can be added to this properties file at any time, updates after the server has started
# will be automatically detected.
#
# The format of this file is as follows: -
# username=role1,role2,role3
#
# A utility script is provided which can be executed from the bin folder to add the users: -
# - Linux
#  bin/add-user.sh
#
# - Windows
#  bin\add-user.bat
#
# The following illustrates how an admin user could be defined.
#
#admin=PowerUser,BillingAdmin,
#guest=guest
#CN\=cmc_fe_uat.marsdctr.hksarg,\ OU\=Digital\ Policy\ Office,\ O\=The\ Government\ of\ the\ HKSAR,\ L\=Hong\ Kong,\ ST\=Hong\ Kong,\ C\=HK=xmlfw-rpc
# cmc_fe_uat.marsdctr.hksarg=xmlfw-rpc
admin=keyservice_admin, keyservice_readonly, recon_txn_admin, pradmin, content_update_internal
slave=keyservice_admin, keyservice_readonly, recon_txn_admin, pradmin, content_update_internal
ejbuser=
scriptUser=guest
sslclient.msg.egisdctr.hksarg=xmlfw-rpc
#CN\=sslclient.msg.egisdctr.hksarg,\ OU\=Digital\ Policy\ Office,\ O\=The\ Government\ of\ the\ HKSAR,\ C\=HK=xmlfw-rpc
