# Daily log rotate
0 0 * * * /bd-ogcmr/uat/cmc/cmc-core/script/cmcRotateBatchJobLog.sh  >> /bd-ogcmr/uat/cmc/cmc-core/script/log/batchjob.log 2>&1

# Housekeep server log -- BEGIN
0 2 * * * /bd-ogcmr/uat/cmc/cmc-core/script/housekeeping_server_log.sh  >> /bd-ogcmr/uat/cmc/cmc-core/script/log/batchjob.log 2>&1
# Housekeep server log -- END

# CMC Log File Check -- BEGIN
0 6 * * * /bd-ogcmr/uat/cmc/cmc-core/script/cmcLogFileCheckJob.sh >> /bd-ogcmr/uat/cmc/cmc-core/script/log/batchjob.log 2>&1
# CMC Log File Check -- END